### PR TITLE
Trees

### PR DESCRIPTION
**Pull request by ZippeyKeys12**
I need the specifications for evaluating our generators.

Parts of particular interest:
- [ ] Imperative deep copy for binary trees
- [ ] Insert for red-black tree
- [ ] Threaded binary trees (or trees with a `parent` pointer)

### CODE REVIEW

**Comment by bcpierce00** [comment]
This looks very nice, Apol.  

I think it would make a good "optional 
extended exercise" in the tutorial, for people that want to practice their simple-functional-specification chops.  I suggest adding some BEGIN/END annotations so that we can generate a version that is just the C code with little to no CN.  (This may involve reorganizing the files a little, since at the moment some  of them contain *only* CN code.)

**Comment by bcpierce00** [comment]
Apologies -- commented on the wrong PR!  Please ignore that...

**Comment by bcpierce00** [comment]
Are these examples intended to be surfaced / explained / used as sources of exercises in the tutorial?  

If so, we should talk.

If not, we should move them to another part of the repo.  (/src/examples, despite its generic name, is where examples specifically for the tutorial live.)

**Comment by ZippeyKeys12** [comment]
The PR is just so that they're somewhere public. Once they're complete, I'm not sure.

There's also the possibility that others will complete them before I get around to it.

**Pull request closed without merging**
