### PR TITLE
Binary Search Tree Data Structure

### PR DESCRIPTION
**Pull request by MedranoApol**

### CODE REVIEW

**Comment by bcpierce00** [comment]
This looks very nice, Apol.

I think it would make a good "optional
extended exercise" in the tutorial, for people that want to practice their simple-functional-specification chops. I suggest adding some BEGIN/END annotations so that we can generate a version that is just the C code with little to no CN. (This may involve reorganizing the files a little, since at the moment some of them contain only CN code.)

**Comment by septract** [comment]
What else is needed to merge this?

**Comment by bcpierce00** [comment]
On a more careful reading, this is a good start toward a BST example, but it its definition of what it means to be a BST is not quite correct.  I'm going to put it on the side for now.

**Comment by bcpierce00** [comment]
(I'll keep the files in an /underconstruction directory, though, in case anybody wants to come back to it later.)

**Pull request closed without merging**
