### PR TITLE
Added CI and a HARDENS instrumentation unit that was causing issues

### PR DESCRIPTION
**Pull request by podhrmic**
* Added basic CI
* Added a file for testing [#283](https://github.com/rems-project/cerberus/issues/283)

### CODE REVIEW

**Comment by podhrmic** [comment]
Note that the CI now fails *because* the test I added leads to an exception, see [this line](https://github.com/GaloisInc/cn-tutorial/actions/runs/9306526085/job/25615913620#step:4:276)

**Comment by septract** [comment]
See [here](https://github.com/rems-project/cn-tutorial/blob/main/src/example-archive/README.md) for how to locate failing / crashing examples so that existing CI will check they elicit the expected return code. You can host this example in either the `simple-examples` subdirectory, or (better) make your own subdirectory `verse-toolchain` for examples coming from TA2.

**Comment by podhrmic** [comment]
FYI [here is the OpenSUT CI](https://github.com/GaloisInc/VERSE-OpenSUT/tree/main/.github/workflows)

I guess I don't understand the `example-archive` folder - the [README](https://github.com/rems-project/cn-tutorial/blob/main/README.md) makes it look like the folder is not used anymore?

**Comment by septract** [comment]
It's run separately as part of the `cerberus` CI, but yeah not documented at the top level of `cn-tutorial`.

**Comment by septract** [comment]
See the setup file [here](https://github.com/rems-project/cerberus/blob/master/.github/workflows/ci.yml) and the (slightly wonky) script [here](https://github.com/rems-project/cerberus/blob/master/tests/run-cn-tutorial-ci.sh). We should probably make this more robust

**Comment by septract** [comment]
@podhrmic would you like me to reshape this into the existing example archive structure?

**Comment by podhrmic** [comment]
Yes please, that would be very helpful.
I looked at the [CI file](https://github.com/rems-project/cerberus/blob/master/.github/workflows/ci.yml) and the steps can certainly be split into multiple different jobs so it runs faster and is more cleanly separated, but that is IMHO low priority now.

**Comment by septract** [comment]
Okay I’ll take a look. The main issue is the CI file doesn’t cover all the examples (I think). Making it more ergonomic can wait yes. On Jun 4, 2024, at 4:14 PM, Michal Podhradsky ***@***.***> wrote:﻿
Yes please, that would be very helpful.
I looked at the CI file and the steps can certainly be split into multiple different jobs so it runs faster and is more cleanly separated, but that is IMHO low priority now.

**Comment by septract** [comment]
Closing this PR as I merged the files into #27

**Pull request closed without merging**
